
[functions.hello-world]
enabled = true
verify_jwt = true
import_map = "./functions/hello-world/deno.json"
entrypoint = "./functions/hello-world/index.ts"

[functions.google-maps-proxy]
enabled = true
verify_jwt = true
entrypoint = "./functions/google-maps-proxy/index.ts"

[functions.log-api-call]
enabled = true
verify_jwt = true
entrypoint = "./functions/log-api-call/index.ts"
